---
################################################################################
# Set your variables here.
################################################################################


#
# role "cron" settings
#
cron_daemon: cronie
elao_cron_files:
  - file: rsnapshot
    user: root
    jobs:
      - name:     rsnapshot-alpha
        job:      "rsnapshot -c /etc/rsnapshot.conf alpha"
        minute:   0
        hour:     "*"
        hour:     "*/2"
      - name:     rsnapshot-beta
        job:      "rsnapshot -c /etc/rsnapshot.conf beta"
        minute:   45
        hour:     23
      - name:     rsnapshot-gamma
        job:      "rsnapshot -c /etc/rsnapshot.conf gamma"
        minute:   30 
        hour:     22
        weekday:  0
      - name:     rsnapshot-delta
        job:      "rsnapshot -c /etc/rsnapshot.conf delta"
        minute:   15
        hour:     21
        day:      1
  - file: os-update
    user: root
    jobs:
      - name:     os-update-download-only
        job:      "/usr/bin/pacman -Syyuwq --noconfirm"
        minute:   10 
        hour:     "*/6"
      - name:     os-update
        job:      "/usr/bin/pacman -Syuq --noconfirm"
        minute:   40
        hour:     "*/12"
  - file: disk-cleanup
    user: root
    jobs:
      - name:     disk-cleanup
        job:      "/usr/bin/pacman -Scc --noconfirm"
        minute:   55
        hour:     0
      - name:     docker-prune
        job:      "docker system prune -a -f"
        minute:   55
        hour:     1
  - file: webmon
    user: mainuser
    jobs:
      - name:     update-information
        job:      "/home/mainuser/files/webmon/update.sh"
        minute:   "*"
        hour:     "*"
