################################################################################
# Set your variables here.
################################################################################


#
# role "ntp_client" settings
#
ntp_client:
  ntp_server: ntp1.ptb.de
