---
################################################################################
# Set your variables here.
################################################################################


#
# role "ansible-role-timezone" settings
#
timezone: Europe/Berlin
