---
################################################################################
# Set your variables here.
################################################################################


#
# role "backup" settings
#
backup:
  files:
    - /run/media/benni/webdav/
  cp_bin: /usr/bin/cp
  rm_bin: /usr/bin/rm
