---
################################################################################
# Set your variables here.
################################################################################


# 
# role "common" settings
#
hostname: server1.home
