common_timezone: 'Etc/UTC'
admin_email: "{{ main_user_name }}@{{ domain }}"
main_user_shell: "/usr/bin/zsh"
friendly_networks:
  - ""

# let's encrypt
letsencrypt_server: "https://acme-v02.api.letsencrypt.org/directory"

# ssh
kex_algorithms: "curve25519-sha256@libssh.org"
host_key_algorithms: "ssh-ed25519"
ciphers: "chacha20-poly1305@openssh.com"
macs: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com"

# ntp
ntp_servers:
  # use nearby ntp servers by default
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
  - 3.pool.ntp.org
  # use servers tailored to the server location
  # See http://www.pool.ntp.org/en/use.html
  # - 0.north-america.pool.ntp.org
  # - 1.north-america.pool.ntp.org
  # - 2.north-america.pool.ntp.org
  # - 3.north-america.pool.ntp.org
