---
# tasks file for monorepo
#
- name: Role - monorepo
  debug:
    msg: "monorepo"
    verbosity: 1

- name: Creates Documents directory
  file:
    path: "~/Documents"
    state: directory
- name: link files
  file:
    src: "~/Documents"
    dest: "~/files"
    state: link
    force: "yes"
- name: monorepo | clone monorepo git repository
  git:
    repo: "{{ monorepo_git_repo }}"
    dest: "{{ monorepo_dest }}"
