[package]
name = "relf"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.9"
structopt = "0.3"
nom = "7"
deku = "0.12"
