---
################################################################################
# Set your variables here.
################################################################################


# 
# role "common" settings
#
hostname: server2.home
