name: benni.tech CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./benni.tech/content

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: show dir
      run: ls -la

    - name: check links
      run: ./check_links.sh


  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./benni.tech

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: show dir
      run: ls -la

    - name: Deploy test site
      id: deploy
      uses: fleekhq/action-deploy@v1
      with:
        apiKey: ${{ secrets.FLEEK_API_KEY }}
    - name: Get the output url
      run: echo "Deploy url is ${{ steps.deploy.outputs.deployUrl }}"
