name: playbooks CI

on: [push, pull_request]

jobs:
  deployment:

    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash
        working-directory: ./deploy/playbooks

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: show dir
      run: ls -la

    - name: initilization
      with: # Set the secret as an input
        GH_SSH_HOME_PUB: ${{ secrets.SSH_HOME_PUB}}
      run: make bootstrap

    - name: local.deploy
      run: make local.deploy
